### ISSUE TITLE
wraparound semantics

### ISSUE THREAD

**Issue by usergoodvery** [rmind/ringbuf#1]
Hi,
I am trying to validate the applicability of this library for my usecase, but I am not clear on the wraparound semantics as you described it.
I have a MPSC setup, where producers will need to save pointers to preallocated addresses (8 byte), so I thought the ring buffer could be used for that, as each producer would request a fixed length 8-byte slot to save the pointer vale to. It appears to me if my ring buffer size is multiple of 8-bytes there wouldn't be wrap around applicable. is that correct understanding?

regards

**Comment by rmind** [comment]
Hi,

Well, the buffer will always have to wrap around at some point.  Do you mean the case when some space at the end of the buffer would be sacrificed to provide a contiguous allocation?  In such case, if the buffer size is dividable by the allocation unit size (assuming it's fixed, e.g. 8 bytes), then it would not happen.  However, since this ring buffer is lock-free, there are some implications -- please see the "Caveats" section in the updated README file.  Also, check the unit tests in the `t_ringbuf.c` file for examples.

P.S. I have changed the API so that it would not assume threads.

**Comment by usergoodvery** [comment]
Thanks you have answered my question. How do you handle a scenario where all the space available is taken up by "busy" producers that have not yielded the space (ie did not call ringbuf_produce(r, tls)), what happens when a new producer tries to acquire allocation from the buffer? 

btw I think it is a smart move to abstract away threads

**Comment by rmind** [comment]
Not sure what exactly is your question. You can think of `ringbuf_acquire` as a reservation, where `ringbuf_produce` is a "commit".  You cannot rollback, though.  If there is no more space left in the ring buffer, then `ringbuf_acquire` will indicate that by returning -1.  It is up to the caller how it handles this situation, because there can be different strategies (e.g. spin-wait and retry, sleep using a conditional variable or an equivalent mechanism, perhaps synchronise using eventfd, etc).

**Comment by rmind** [comment]
Resolved.
